import assert from 'node:assert/strict';
import { createEpisodeFixture } from '../app/data/episode.js';
import { workspaceFromEpisode, episodeFromWorkspace, extractClinicalFactsFromDocuments, applyPatientContext, applyDocumentFacts } from '../app/p1/current-case-adapter.js';
import { runPreGrouping, runFormalGrouping, runAuditAgainstFormal } from '../app/p1/workflow-orchestrator.js';
import { searchDip3DiagnosisCatalog } from '../app/p1/dip3-grouper.js';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const base=createEpisodeFixture();
let w=workspaceFromEpisode(base,{policyProfileId:'WH-DRG-3.0'});w.patient.age=47;
let e=episodeFromWorkspace(base,w);let pre=runPreGrouping({episode:e,workspace:w});
assert.equal(pre.route.paymentMethod,'DRG');assert.equal(pre.groupingResult.group.code,'HC45');
w.principalDiagnosis={code:'K80.302',name:'胆总管结石伴胆管炎'};w.secondaryDiagnoses=[{code:'I50.900',name:'心力衰竭'}];w.revision=2;e=episodeFromWorkspace(base,w);pre=runPreGrouping({episode:e,workspace:w});assert.equal(pre.groupingResult.group.code,'HC43');
w.claimDetails=[{id:'A',category:'examination',itemCode:'ITEM001',itemName:'检查项目',billingTime:String(base.admission.at).slice(0,10)+'T10:00:00+08:00',quantity:1,unitPrice:100,amount:100,aggregateSource:false},{id:'B',category:'examination',itemCode:'ITEM001',itemName:'检查项目',billingTime:String(base.admission.at).slice(0,10)+'T10:00:00+08:00',quantity:1,unitPrice:100,amount:100,aggregateSource:false},{id:'C',category:'laboratory',itemCode:'ITEM002',itemName:'化验项目',billingTime:'2030-01-01T10:00:00+08:00',quantity:1,unitPrice:80,amount:80,aggregateSource:false}];w.localPaymentParameters={weight:1.2,rate:10000,adjustment:1};w.revision=3;e=episodeFromWorkspace(base,w);const formal=runFormalGrouping({episode:e,workspace:w});assert.equal(formal.groupingResult.group.code,'HC43');assert.equal(formal.paymentResult.amount,12000);const audit=runAuditAgainstFormal({episode:e,workspace:w,formalRun:formal});assert.ok(audit.risks.some(x=>x.type==='CLAIM_DETAIL_DUPLICATE'));assert.ok(audit.risks.some(x=>x.type==='CLAIM_DETAIL_TIME'));assert.ok(audit.risks.some(x=>x.type==='DRG_GROUPING_IMPACT'));
w.policyProfileId='DIP-3.0-TEST';w.secondaryDiagnoses=[];w.revision=4;e=episodeFromWorkspace(base,w);const dip=runPreGrouping({episode:e,workspace:w});assert.equal(dip.route.paymentMethod,'DIP');assert.equal(dip.groupingResult.group.code,'BX-1029');
const facts=extractClinicalFactsFromDocuments([{templateId:'frontpage',templateName:'住院病案首页',snapshot:{data:[{keyName:'主要诊断',keyValue:'胆总管结石伴胆管炎'},{keyName:'主要诊断疾病编码',keyValue:'K80.302'},{keyName:'主要手术及操作代码',keyValue:'51.2300'}]}}]);assert.equal(facts.mainDiagnosis.code,'K80.302');assert.equal(facts.mainProcedure.code,'51.2300');
const selected=applyPatientContext(base,{episodeId:'EP-DEMO-006',name:'周某某',sex:'男',age:36});assert.equal(applyDocumentFacts(selected,extractClinicalFactsFromDocuments([])).patient.age,36,'missing saved age must preserve the active patient age');
const mapped=applyDocumentFacts(selected,extractClinicalFactsFromDocuments([{templateId:'frontpage',templateName:'住院病案首页',snapshot:{data:[{keyName:'年龄',keyValue:'52岁'},{keyName:'主要诊断代码',keyValue:'K80.302'},{keyName:'主要手术及操作代码',keyValue:'51.2300'}]}}]));assert.equal(mapped.patient.age,52);assert.equal(mapped.diagnoses.principal.code,'K80.302');assert.equal(mapped.procedures[0].code,'51.2300');
const diagnosis=searchDip3DiagnosisCatalog('K80.1').find(x=>x.code==='K80.1');assert.ok(diagnosis,'official DIP 3.0 catalogue includes ICD-coded diagnoses');assert.ok(searchDip3DiagnosisCatalog(diagnosis.name).some(x=>x.code===diagnosis.code),'diagnoses can be searched by Chinese name');
const workbench=readFileSync(new URL('../app/p1-operational-workbench.js',import.meta.url),'utf8');assert.match(workbench,/data-op-patient-select/);assert.match(workbench,/data-open-diagnosis-picker/);assert.match(workbench,/data-diagnosis-code/);assert.doesNotMatch(workbench,/地方支付参数（可选测试，不冒充生产参数）|local\.weight|local\.rate/);
execFileSync(process.execPath,['--input-type=module','--check'],{input:workbench});
console.log('PASS P1 operational workbench pipeline');
