import { strict as assert } from 'node:assert';
import { createEpisodeFixture } from '../app/data/episode.js';
import { buildSettlementList, validateSettlementList } from '../app/domain/settlement.js';
import { renderSettlementPaper } from '../app/domain/settlement-template.js';
const list = buildSettlementList(createEpisodeFixture());
const issues = validateSettlementList(list);
assert.ok(Array.isArray(issues));
const html = renderSettlementPaper(list);
assert.match(html, /第 1 页 \/ 共 3 页/);
assert.match(html, /第 2 页 \/ 共 3 页/);
assert.match(html, /第 3 页 \/ 共 3 页/);
assert.match(html, /医疗保障基金结算清单/);
console.log('PASS settlement template');
